### ISSUE TITLE
[New-Playbook] T1052.001 - Exfiltration over USB

### ISSUE THREAD

**Issue by austinsonger** [austinsonger/Incident-Playbook#71]
- https://github.com/austinsonger/Incident-Playbook/blob/main/Playbooks/MITRE-ATTACK/Exfiltration/T1052%20-%20Exfiltration%20Over%20Physical%20Medium/T1052.001%20-%20Exfiltration%20over%20USB.md

### Checklist

- [ ] Investigate
- [ ] Remediate
- [ ] Communicate
- [ ] Recover

**Comment by sn0b4ll** [comment]
Working on this :)
